# Site settings
title: Soon 2B Salita
name: Soon To Be The Salitas
description: Michael and Lizzie 2017
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "signedsealedsalita.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
